### ISSUE TITLE
国外tracker分享博客站，希望添加

### ISSUE THREAD

**Issue by OR120** [XIU2/TrackersListCollection#1]
https://tinytorrent.net/best-torrent-tracker-list-updated
https://torrenttrackerss.com/torrent-tracker-list
http://www.torrenttrackerlist.com/torrent-tracker-list

**Comment by XIU2** [comment]
已收到，稍后会添加的。

**Comment by XIU2** [comment]
@OR120 已添加 [#857633b](https://github.com/XIU2/TrackersListCollection/commit/857633b1b1ff6a5d1fa79f1bdd9d13833a2b8937)，同时优化了以下内容：
去除了一些没照顾到的重复项（如 http://xxx.xx:80/announce 和 http://xxx.xx/announce 这样的，去除了后者，减少了大概 50+ 个重复项）
