### ISSUE TITLE
看到个中国境内的ACG TrackersList 望整合

### ISSUE THREAD

**Issue by GysdfHome** [XIU2/TrackersListCollection#10]
https://gitee.com/banbendalao/hosts_optimize_tracker_links

**Comment by XIU2** [comment]
看了下，这个项目已经停止维护了，超过 9 个月没有更新了。

**Comment by SKIYET** [comment]
Dear

it is alive now. Last upate of that project is 7 days ago.

**Comment by WhiCCX0** [comment]
活啦活啦

**Comment by XIU2** [comment]
@WhiCCX0 

又去看了下，该项目也是对其他的 TrackerList 项目进行整合。
而且该项目已经整合了本项目，我要是再整合该项目，那就是**套娃无限循环**了。

除了本项目外，该项目整合的其他 TrackerList，除了 [yaozuopan] 外，**其他的都已经整合进本项目了**。
该项目只是对 Tracker 进行了**去重（复）**，而本项目则还有其他筛选机制，也就是说本项目整合过程中去除掉的无效 Trakcer 又被该项目加回去了。。。
