### ISSUE TITLE
Suggest to add Tracker source.

### ISSUE THREAD

**Issue by RivenNero** [XIU2/TrackersListCollection#12]
Suggest to add Tracker source: https://github.com/DeSireFire/animeTrackerList

**Comment by XIU2** [comment]
Thanks for providing, has been added!
[#tracker-source](https://github.com/XIU2/TrackersListCollection#tracker-source)

**Comment by HanadaLee** [comment]
我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。

**Comment by XIU2** [comment]
> 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。

你的 Tracker URL 是什么？
DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。

**Comment by HanadaLee** [comment]
他那个项目是直接采集动漫花园、ACG.RIP、NYAA等国内知名的ACG种子站里的种子然后提取里面的Tracker列表并去重采集来的，我的Tracker被他收录估计也是因为采集来的，估计格式乱七八糟也是这个原因，我的Tracker主要还是供我字幕组使用的，就先不提供了。

**Comment by HanadaLee** [comment]
> > 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。
> 
> 你的 Tracker URL 是什么？
> DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。

说起来我有点想知道这个项目的收录Tracker的原理。。。上周我的Tracker貌似又被收录了，然后过了两天就又被删除了。这是在帮我的Tracker做压测么。。。

**Comment by XIU2** [comment]
> > > 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。
> > 
> > 
> > 你的 Tracker URL 是什么？
> > DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。
> 
> 说起来我有点想知道这个项目的收录Tracker的原理。。。上周我的Tracker貌似又被收录了，然后过了两天就又被删除了。这是在帮我的Tracker做压测么。。。

我不做单独收录，我只是把其他的 TrackersList 整合在一起了，你说的情况，应该是你的 Tracker 被 DeSireFire/animeTrackerList 的 best.txt 收录了，随后又删除了。

**Comment by HanadaLee** [comment]
> > > > 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。
> > > 
> > > 
> > > 你的 Tracker URL 是什么？
> > > DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。
> > 
> > 
> > 说起来我有点想知道这个项目的收录Tracker的原理。。。上周我的Tracker貌似又被收录了，然后过了两天就又被删除了。这是在帮我的Tracker做压测么。。。
> 
> 我不做单独收录，我只是把其他的 TrackersList 整合在一起了，你说的情况，应该是你的 Tracker 被 DeSireFire/animeTrackerList 的 best.txt 收录了，随后又删除了。

原来如此，既然他们这么喜欢反复横跳，那我就直接丢出来好了，反正也不缺这点计算资源。天天看到CPU反复横跳感觉就很不舒服23333

https://tracker.tamersunion.org/announce

**Comment by XIU2** [comment]
> > > > > 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。
> > > > 
> > > > 
> > > > 你的 Tracker URL 是什么？
> > > > DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。
> > > 
> > > 
> > > 说起来我有点想知道这个项目的收录Tracker的原理。。。上周我的Tracker貌似又被收录了，然后过了两天就又被删除了。这是在帮我的Tracker做压测么。。。
> > 
> > 
> > 我不做单独收录，我只是把其他的 TrackersList 整合在一起了，你说的情况，应该是你的 Tracker 被 DeSireFire/animeTrackerList 的 best.txt 收录了，随后又删除了。
> 
> 原来如此，既然他们这么喜欢反复横跳，那我就直接丢出来好了，反正也不缺这点计算资源。天天看到CPU反复横跳感觉就很不舒服23333
> 
> https://tracker.tamersunion.org/announce

如果你需要我可以默认筛选掉你的 Tracker，或者把你的 Tracker 添加到我的 TrackersList ？

**Comment by HanadaLee** [comment]
> > > > > > 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。
> > > > > 
> > > > > 
> > > > > 你的 Tracker URL 是什么？
> > > > > DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。
> > > > 
> > > > 
> > > > 说起来我有点想知道这个项目的收录Tracker的原理。。。上周我的Tracker貌似又被收录了，然后过了两天就又被删除了。这是在帮我的Tracker做压测么。。。
> > > 
> > > 
> > > 我不做单独收录，我只是把其他的 TrackersList 整合在一起了，你说的情况，应该是你的 Tracker 被 DeSireFire/animeTrackerList 的 best.txt 收录了，随后又删除了。
> > 
> > 
> > 原来如此，既然他们这么喜欢反复横跳，那我就直接丢出来好了，反正也不缺这点计算资源。天天看到CPU反复横跳感觉就很不舒服23333
> > https://tracker.tamersunion.org/announce
> 
> 如果你需要我可以默认筛选掉你的 Tracker，或者把你的 Tracker 添加到我的 TrackersList ？

加吧

**Comment by XIU2** [comment]
> > > > > > > 我还说怎么最近我的Tracker用户激增然后现在又没了，原来是这里收录过。
> > > > > > 
> > > > > > 
> > > > > > 你的 Tracker URL 是什么？
> > > > > > DeSireFire/animeTrackerList 这个列表，加入后发现质量有点差(最明显的是各种格式错误无法直视)，反应不太好，所以我把收录 all 列表改成了 best 列表了。
> > > > > 
> > > > > 
> > > > > 说起来我有点想知道这个项目的收录Tracker的原理。。。上周我的Tracker貌似又被收录了，然后过了两天就又被删除了。这是在帮我的Tracker做压测么。。。
> > > > 
> > > > 
> > > > 我不做单独收录，我只是把其他的 TrackersList 整合在一起了，你说的情况，应该是你的 Tracker 被 DeSireFire/animeTrackerList 的 best.txt 收录了，随后又删除了。
> > > 
> > > 
> > > 原来如此，既然他们这么喜欢反复横跳，那我就直接丢出来好了，反正也不缺这点计算资源。天天看到CPU反复横跳感觉就很不舒服23333
> > > https://tracker.tamersunion.org/announce
> > 
> > 
> > 如果你需要我可以默认筛选掉你的 Tracker，或者把你的 Tracker 添加到我的 TrackersList ？
> 
> 加吧

已经加上了。[#5047996](https://github.com/XIU2/TrackersListCollection/commit/5047996117b902d693166d5199809e4b764f8c18)
