### ISSUE TITLE
一些错误

### ISSUE THREAD

**Issue by mrdobejelly** [XIU2/TrackersListCollection#13]
http://bt.dmhy.net/annonuce
http://ipv4.tracker.harry.lu/annouce
http://share.dmhy.me/annonuce
上面三个的announce全部拼写有误
udp:/ndrotracker.biz:1337/announce少了一个/

**Comment by mrdobejelly** [comment]
udp:/ntost12.xyz:6969/announce

udp:/tracker.org:6969/announce
这两个也一样

**Comment by XIU2** [comment]
这是前几天新添加的 Trackerslist 源的锅。。。
这个源质量有点低，各种格式错误（像你这个、还有什么把端口冒号写成点的。。。），都给我整懵逼了，稍后我过滤一下。

**Comment by XIU2** [comment]
已更新，这几个错误的已经清除掉了。
另外，鉴于 DeSireFire/animeTrackerList 源质量低，我将不再使用其 all 列表，只使用 best 列表。
