### ISSUE TITLE
The trackers project on gitee is alive.

### ISSUE THREAD

**Issue by SKIYET** [XIU2/TrackersListCollection#16]
Dear

The project : https://gitee.com/banbendalao/hosts_optimize_tracker_links

it is alive now. Last upate of that project is 7 days ago.

**Comment by XIU2** [comment]
After a period of observation, the project cannot meet my minimum requirements, such as: the update frequency is too low, and the quality cannot be guaranteed.
Therefore, the project will not be considered for the time being.
