### ISSUE TITLE
precheck each tracker before publising

### ISSUE THREAD

**Issue by mrx23dot** [XIU2/TrackersListCollection#18]
master/best.txt contains invalid trackers, please filter it before upload.
eg udp://tracker.0o.is:6969/announce	No such host is known.

you could do simply:
ping tracker.0o.is
"Ping request could not find host tracker.0o.is. Please check the name and try again."

**Comment by XIU2** [comment]
Has added to-do list.

**Comment by XIU2** [comment]
After checking, tracker.0o.is points to IPv6.
If your device does not have IPv6, you cannot use `Ping tracker.0o.is` .
Please use `host tracker.0o.is` or `nslookup tracker.0o.is` instead (Linux).

**Comment by XIU2** [comment]
Now, unresolved domain names will be filtered out.
