### ISSUE TITLE
你好!

### ISSUE THREAD

**Issue by acdc126** [XIU2/TrackersListCollection#2]
这3个地址360报警.
udp://ulfbrueggemann.no-ip.org:6969/announce
udp://caramelo.ddns.net:8000/announce
http://nbz.f3322.net:36006/announce
比特彗星看更新1.6了,可以更新一下吗? 1.59 用着用着自己要崩溃!

**Comment by XIU2** [comment]
报警理由是什么？

我不用 360，我使用的是 火绒+Defender(Win10自带)。
经过检查：
- ulfbrueggemann.no-ip.org 不可用（域名无指向IP）
- caramelo.ddns.net 解析正常(等我稍后详细检查下)
- nbz.f3322.net 解析异常（大部分地区无指向IP，个别地区被运营商劫持为当地运营商IP或 127.0.0.1）

1.60 版本没什么改进，紧接着就出现了 1.61 版本，目前还属于测试版，等 1.61 稳定了我就会出解锁版的。

**Comment by acdc126** [comment]
谢谢!回复
日志清理了.找不到了.没多大问题!
那只有等 1.61了.谢谢!

**Comment by XIU2** [comment]
[#28c4e9f](https://github.com/XIU2/TrackersListCollection/commit/28c4e9f620c69cce9cdda96af85303624328a556) 已更新。  

## 更新说明：

- **1. 新增** 黑名单功能（有问题或者劣质的将会被去除）。  
- **2. 删除** 三个域名（你提交的域名，去除理由分别是(全球)：不可用、解析异常、可用性极低）  
- **3. 优化** Tracker 质量，去除近百个已失效或可用性极低的 Tracker 服务器。

**Comment by XIU2** [comment]
@acdc126 1.61 正式版前几天出来了，我先做了个 1.61 的解锁版。
下载地址没变：https://www.lanzous.com/b073c7g4f

该版本主要是修复一些BUG、新增RSS订阅、端口封禁功能（已封禁 15000 迅雷吸血版本端口）
