### ISSUE TITLE
请求添加 Tracker 源

### ISSUE THREAD

**Issue by EA-DICE** [XIU2/TrackersListCollection#20]
希望添加以下 Tracker 源：
https://github.com/DeSireFire/animeTrackerList
在此前的issues中，我发现作者好像只收录了best list，原因是排版以及格式错误过多，现在我发现all list格式较为整齐，希望作者检查一下格式是否符合要求，考虑将all list添加到本项目中

**Comment by XIU2** [comment]
看了下，依然和以前一样，大概看了下就看到了好几个：
- [AT_all.txt#L77](https://github.com/DeSireFire/animeTrackerList/blob/master/AT_all.txt#L77) 端口前面缺少冒号
- [AT_all.txt#L85](https://github.com/DeSireFire/animeTrackerList/blob/master/AT_all.txt#L85)非 Tracker 内容
- [AT_all.txt#L113](https://github.com/DeSireFire/animeTrackerList/blob/master/AT_all.txt#L113)端口前面应该是冒号而不是点

**Comment by EA-DICE** [comment]
已知悉，感谢

**Comment by EA-DICE** [comment]
我将向desirefire反馈
