### ISSUE TITLE
AniRena should not be added as "public" tracker - AniRena不應添加為“公共”跟踪器

### ISSUE THREAD

**Issue by Power2All** [XIU2/TrackersListCollection#21]
Hi,

I am the founder and owner of AniRena.com and noticed you added the AniRena tracker to your listing.
This will not work, unless the torrent has been uploaded directly to AniRena, it's a "partial" public tracker, it allows you to upload anonymously a torrent, but the torrent will only get active on the tracker when it's uploaded at all.

Hope this is informative enough.

Kind regards.

======

你好

我是AniRena.com的創始人和所有者，並註意到您將AniRena跟踪器添加到了您的列表中。
這是行不通的，除非將種子直接上傳到AniRena，這是一個“部分”公共跟踪程序，它允許您匿名上傳一個種子，但是當種子完全上傳後，該種子將僅在跟踪器上處於活動狀態。

希望這能提供足夠的信息。

親切的問候。

**Comment by XIU2** [comment]
Upon inspection, `http://tracker.anirena.com:80/announce` comes from the [DeSireFire/animeTrackerList](https://github.com/DeSireFire/animeTrackerList) project.  
The Tracker server has been removed and added to the [blacklist](https://github.com/XIU2/TrackersListCollection/blob/master/blacklist.txt).
****
经过检查， `http://tracker.anirena.com:80/announce` 来自 [DeSireFire/animeTrackerList](https://github.com/DeSireFire/animeTrackerList) 项目。  
该 Tracker 服务器已经移除，并将其添加到[黑名单](https://github.com/XIU2/TrackersListCollection/blob/master/blacklist.txt)中。

**Comment by Power2All** [comment]
Thanks for the fast response, good luck with the project !
