### ISSUE TITLE
New node of monocul.us

### ISSUE THREAD

**Issue by lupettohf** [XIU2/TrackersListCollection#22]
In your list you already have udp://zephir.monocul.us:6969/announce, we added a new node to have better redundancy and latency. 

udp://abufinzio.monocul.us:6969/announce (Servers are syncronized)

**Comment by XIU2** [comment]
Sorry, the purpose of this project is to integrate other Trackers List projects, and not strictly maintain each Tracker.
***please submit Tracker to the following projects:***

- https://github.com/ngosang/trackerslist
- https://newtrackon.com/
(The website supports manual submissions and monitors Tracker's availability in real time.)
