### ISSUE TITLE
Hello. 

### ISSUE THREAD

**Issue by sloslo4** [XIU2/TrackersListCollection#23]
Awesome lists! Thanks you. Can you put these too for pi-hole ad-blocker?

here sed regexp for convert all.txt to following to just DNS names (valid to pihole):

`(http://|udp://|https://|\[*.+]:.+[0-9]|/announce|:.+[0-9])`

Thank you!

**Comment by XIU2** [comment]
Sorry, I don't quite understand.
Why use the Tracker server as an ad blocker?

**Comment by sloslo4** [comment]
Noo sorry for misunderstood. 
I google these by "torrent trackers pihole lists" and found this repo :)

I mean in corporate networks such lists can help prevent unauthorized torrent download\upload. 
If you block Trackers by list on local DNS server.

**Comment by XIU2** [comment]
Disabling Tracker does not prevent BT download.
BT obtains users through DHT, Peer and Tracker.
The functions of the three are complementary.

Disabling Tracker can only reduce the BT download speed.
