### ISSUE TITLE
我从许多热门种子收集了大量的tracker链接，希望对你有用

### ISSUE THREAD

**Issue by RxinnotRstar** [XIU2/TrackersListCollection#24]
[https://github.com/RxinnotRstar/Rxinns/blob/master/Rxinns%E6%94%B6%E9%9B%86%E7%9A%84tracker%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%88%E9%9A%8F%E7%BC%98%E6%9B%B4%E6%96%B0%EF%BC%81%EF%BC%89.txt](url)

**Comment by RxinnotRstar** [comment]
这份txt是给我自己用于比特彗星自动更新的，现在分享出来

**Comment by XIU2** [comment]
简单看了下，和本项目当前的 Tracker 地址有很多重复的，不清楚质量怎么样，更新是否稳定等。
会考虑添加的。
