### ISSUE TITLE
qBittorren Enhanced Edition 4.2.5.12 refresh报错

### ISSUE THREAD

**Issue by blackforest1840** [XIU2/TrackersListCollection#25]
![image](https://user-images.githubusercontent.com/38518660/84751916-b5c73f80-afef-11ea-890b-c817bbd462aa.png)
如图所示，按照教程粘贴链接后refresh或者直接apply就会显示乱码，无法正常更新tracker

**Comment by XIU2** [comment]
我使用 qbee 一切正常。
![1](https://user-images.githubusercontent.com/54703944/84849201-63d1f880-b087-11ea-86c6-4bcaa235c940.png)

**Comment by EA-DICE** [comment]
> 我使用 qbee 一切正常。
> ![1](https://user-images.githubusercontent.com/54703944/84849201-63d1f880-b087-11ea-86c6-4bcaa235c940.png)

是否会是dns问题？

**Comment by XIU2** [comment]
@EA-DICE 都有可能，主要是 1L 没有提供更多的信息，我无法判断。
