### ISSUE TITLE
建议出一个去除udp tracker的列表

### ISSUE THREAD

**Issue by OR120** [XIU2/TrackersListCollection#26]
建议出一个去除udp tracker的列表，从1.68版本开始，由于比特彗星使用大量的udp tracker会导致出现大量请求，直接堵住队列发不出去，从而造成比特彗星未响应，从彗星官方论坛得知是udp和udp tracker导致的

**Comment by XIU2** [comment]
[#bede8d8](https://github.com/XIU2/TrackersListCollection/commit/bede8d8075f60647b82a781e5a3595e6df849e61) updated.
## Project Update:
- **Add** HTTP(S) Tracker list.  
> https://trackerslist.com/http.txt  
> https://trackerslist.com/http_aria2.txt  
****
- **添加** HTTP(S) Tracker列表。  
> https://trackerslist.com/http.txt  
> https://trackerslist.com/http_aria2.txt
