### ISSUE TITLE
我发现了一个tracker地址，希望能添加

### ISSUE THREAD

**Issue by Queen-Q** [XIU2/TrackersListCollection#27]
https://dns.icoa.cn/tracker/

**Comment by XIU2** [comment]
emmm，该项目只是把其他 热门Tracker 列表项目 集合在了一起（经过过滤），而不是严格维护每个Tracker。  

**所以，请向以下项目提交Tracker：**
- https://github.com/ngosang/trackerslist  
- https://newtrackon.com/  
（该网站支持手动提交并实时监视 Tracker 的可用性。）
