### ISSUE TITLE
gitte上的一个公共跟踪器列表

### ISSUE THREAD

**Issue by Tool-number** [XIU2/TrackersListCollection#28]
在gitte发现的一个同样的项目，已经收集了大概500个tacker，自己测试效果不错，感觉可以合并起来使用

**Comment by Tool-number** [comment]
https://gitee.com/banbendalao/hosts_optimize_tracker_links

**Comment by XIU2** [comment]
这个项目已经整合了我的项目。
这个项目整合的 6 个Tracker列表中，有 5 个我的项目都已经整合了（包括本项目），而且我的项目已经去掉了几百个无效 Tracker 了，结果它这个项目又给加回来了。。。
