### ISSUE TITLE
建议取消wss://的地址

### ISSUE THREAD

**Issue by qwerttvv** [XIU2/TrackersListCollection#3]
最后三个wss://地址客户端不能识别，建议取消，不然自动更新列表的话又会加入客户端这三个不可识别地址

**Comment by XIU2** [comment]
比特彗星会自动剔除 wss:// 的 Tracker 地址，至于其他 BT 软件， **即使不支持也不会影响其软件正常运行** ，所以没必要剔除。

> 全球公共 WebSocket 协议的 Tracker 服务器目前就这三个，由 [WebTorrent](https://webtorrent.io/) 于 2013 年发起。
