### ISSUE TITLE
Request to add Tracker Source

### ISSUE THREAD

**Issue by JeremiSharkboy** [XIU2/TrackersListCollection#30]
Hope to add these Tracker sources:
ipv4/ipv6 =>

http://jsb.by:8000/announce
udp://jsb.by:8000
ws://jsb.by:8000

**Comment by XIU2** [comment]
Sorry, the purpose of this project is to integrate other Trackers List projects, **and not strictly maintain each Tracker.**

**please submit Tracker to the following projects:**

* https://github.com/ngosang/trackerslist
* https://newtrackon.com/
(The website supports manual submission.)

**Comment by JeremiSharkboy** [comment]
ahh. sry. close please
