### ISSUE TITLE
列表网页无法访问

### ISSUE THREAD

**Issue by atomsyoung** [XIU2/TrackersListCollection#31]
导致客户端无法更新列表

**Comment by XIU2** [comment]
啊咧，没看到你这个 Issues ...  

当天就解决了，是因为我为了提高网站访问速度，就给转移到 Vercel 服务器了（提供免费静态网站部署），结果才用了不到三天，就给我账户封了。。。  
也完全没有通知我或者告诉我原因，也是别人跟我说网站挂了我才发现的。

当时我就发邮件询问了，直到今天（刚才），才回复我邮件，告诉我是网站流量太大就给关了。。。  
最重要的是封号就算了，竟然根本不通知，瞬间印象负分，一生黑。。。

**Comment by atomsyoung** [comment]
感谢
