### ISSUE TITLE
Request to add Tracker

### ISSUE THREAD

**Issue by owner** [XIU2/TrackersListCollection#32]
```
http://tracker.darli.net:5181/announce
udp://tracker.darli.net:5181
```

**Comment by XIU2** [comment]
Sorry, the purpose of this project is to integrate other Trackers List projects, **and not strictly maintain each Tracker.**

**please submit Tracker to the following projects:**

* https://github.com/ngosang/trackerslist
* https://newtrackon.com/
(The website supports automatic submission.)
