### ISSUE TITLE
torrents.io site

### ISSUE THREAD

**Issue by petesimon** [XIU2/TrackersListCollection#33]
the link https://torrents.io/tracker-list/ on your web page is dead.

**Comment by XIU2** [comment]
After testing, the website is no longer accessible due to its own problems.  
I will wait a few more days, and if it still does not return to normal, **the Tracker source will be deleted!**

**Comment by XIU2** [comment]
- **Remove** Tracker source.  
> https://torrents.io/tracker-list/  
> **reason:** The site is not accessible (After a week of waiting).
