### ISSUE TITLE
问一下!主页分享软件的地址打不开了!还会更新吗?

### ISSUE THREAD

**Issue by acdc126** [XIU2/TrackersListCollection#34]
问一下!主页分享软件的地址打不开了!还会更新吗?

**Comment by XIU2** [comment]
你指的是哪些蓝奏云网盘链接？  
我可以正常打开，如果你打开白屏，可能是广告屏蔽扩展的锅（请把蓝奏云网盘添加到广告屏蔽白名单中）。

**Comment by acdc126** [comment]
...哦那可以是我的问题.地址没有问题.没注意.谢谢了!
