### ISSUE TITLE
HTTPS Tracker

### ISSUE THREAD

**Issue by AzukaChan** [XIU2/TrackersListCollection#35]
`https://bitstorm.azukachan.com/announce.php` - Torrent Tracker

**Comment by XIU2** [comment]
Sorry 😂, the purpose of this project is to integrate other Trackers List projects, **and not strictly maintain each Tracker.**

**please submit Tracker to the following projects:**

* https://github.com/ngosang/trackerslist
* https://newtrackon.com/
(The website supports automatic submission.)
