### ISSUE TITLE
你好，我发现了一个中国大陆可用的Tracker地址列表

### ISSUE THREAD

**Issue by zwmain** [XIU2/TrackersListCollection#37]
他们也是每天更新，希望可以合并进去
https://www.yaozuopan.top/dynamic/trackerlist.txt

他们的主页：
https://www.yaozuopan.top/index.php/archives/1014/

**Comment by XIU2** [comment]
测试了下还可以，这个列表中 289 个其中有 182 个和本项目重复的，还有 107 个没有重复的。
重复率不高，已添加到 `all.txt` 中，不过可能需要今天晚些时候本项目 Tracker 列表才会更新。

****

## Project Update: 2020/12/11

- **Add** Tracker source.  
> https://www.yaozuopan.top/dynamic/trackerlist.txt  
- **Optimize** Tracker quality.  
> Now some invalid UDP Tracker will be cleared automatically. *(Expected to clear 30+)*  
****
- **添加** Tracker 源。  
> https://www.yaozuopan.top/dynamic/trackerlist.txt
- **优化** Tracker 质量。  
> 现在将会自动清除部分无效的 UDP Tracker。*(预计清除 30+)*
