### ISSUE TITLE
请求添加 TrackersList(源)

### ISSUE THREAD

**Issue by MysteryMulberry** [XIU2/TrackersListCollection#40]
希望添加以下 TrackersList(源)：
http://tracker1.itzmx.com:8080/announce
http://tracker2.itzmx.com:6961/announce
http://tracker3.itzmx.com:6961/announce
http://tracker4.itzmx.com:2710/announce
udp://tracker1.itzmx.com:8080/announce
udp://tracker2.itzmx.com:6961/announce
udp://tracker3.itzmx.com:6961/announce
udp://tracker4.itzmx.com:2710/announce
http://tracker.opentrackr.org:1337/announce

**Comment by XIU2** [comment]
all.txt 中已包含这些 Tracker。

另外本项目只接受提交 Tracker 列表源（项目），而不接受提交单独的 Tracker 地址。
