### ISSUE TITLE
Add BiglyBT to readme

### ISSUE THREAD

**Issue by Technetium1** [XIU2/TrackersListCollection#42]
Source: https://github.com/BiglySoftware/BiglyBT
Homepage: https://www.biglybt.com/
![image](https://user-images.githubusercontent.com/9877150/106840205-af183600-666d-11eb-98c3-bd4bffbc976a.png)

**Comment by XIU2** [comment]
Sorry. 

Most of the users of this project are **Chinese users** (including me), and I tried to install your software, but the download speed was **very slow** during the installation, and later even directly prompted an error to abort the installation. . .

![1](https://user-images.githubusercontent.com/54703944/106850139-ee3a9b80-66ee-11eb-97f5-cb35bf57663d.png)![2](https://user-images.githubusercontent.com/54703944/106850153-f2ff4f80-66ee-11eb-925c-f77e1da8f88a.png)

**Comment by Technetium1** [comment]
@XIU2 That's very strange, I've been on a VPN in Hong Kong before and have used many CDNs internationally without any speed issues. You can use [the latest GitHub release](https://github.com/BiglySoftware/BiglyBT/releases/latest) to install. If that download is slow you can be sure it is your connection! This is built with Java, so it is required to install. Thank you for your efforts.

**Comment by XIU2** [comment]
After installing JAVA, BiglyBT can be installed normally.

Does BiglyBT support subscribing to Trackers List URL?

**Comment by Technetium1** [comment]
Yes, in the screenshot is the location to add them. `Swarm Discoveries` should be installed by default, if it is not you can get it from [the plugin download page](https://plugins.biglybt.com/). After clicking `Edit Tracker Source List` you add the list you want under `*`.

After looking deeper [at this wiki page](https://github.com/BiglySoftware/BiglyBT/wiki/Tracker-Templates-and-Lists#tracker-list) I'm questioning the correct answer but I'm assuming it to be:
```
*
trackerlist:https://trackerslist.com/all.txt
```
Apologies for the bother, but could you please advise the correct syntax @parg?

**Comment by XIU2** [comment]
I cannot see the [Edit Tracker Source List] button. . .

![1](https://user-images.githubusercontent.com/54703944/106875402-99f4e300-6711-11eb-800e-d53f109f58b3.png)

**Comment by XIU2** [comment]
I have filled in the format you provided, but when I tried to download BT, I did not see the new tracker.

**Comment by Technetium1** [comment]
You did not enable external trackers, you can not edit what does not exist yet. You must choose the tracker sources to have some to edit.

**Comment by Technetium1** [comment]
> I have filled in the format you provided, but when I tried to download BT, I did not see the new tracker.

In this case I think it is best to wait for parg to comment, as I cannot read the source well enough to know the formatting/syntax it expects then

**Comment by XIU2** [comment]
After simple use, I personally feel that the operation is too cumbersome and not friendly to novices.

If there are more simple and friendly operations in the future, I will consider adding it to README.md.

Sorry.

**Comment by parg** [comment]
Not 100% sure of what you're trying to achieve here... 

If you want to automatically add trackers from a tracker list to all of your downloads then the way to do this is discussed here:

https://github.com/BiglySoftware/BiglyBT/wiki/Tracker-Templates-and-Lists

I've created an example Tag that can be imported into BiglyBT by File->Open->BiglyBT File... that will add all the trackers from https://trackerslist.com/all.txt to any downloads that are assigned to the Tag - it is under the 'Known Lists' section.

It is nothing to do with Swarm Discoveries - those 'tracker sources' are simply used to filter Swarm Discovery results.
