### ISSUE TITLE
please remove these trackers

### ISSUE THREAD

**Issue by jamiew0w** [XIU2/TrackersListCollection#43]
i intentionally disabled http/https on my trackers almost a year ago but it appears this repo doesn't do any testing.

http://t1.leech.ie:80/announce
http://t2.leech.ie:80/announce
http://t3.leech.ie:80/announce

https://t1.leech.ie:443/announce
https://t2.leech.ie:443/announce
https://t3.leech.ie:443/announce

udp is enabled if you want to keep them, if not please remove http/https or blacklist them or whatever you want as they do not work.

**Comment by XIU2** [comment]
Thank you for your reminder!

I only found one of the trackers. It has been removed.
`http://t2.leech.ie:80/announce`

At the same time, I also added the Tracker you provided to [blacklist.txt](https://github.com/XIU2/TrackersListCollection/blob/master/blacklist.txt) !

**Comment by jamiew0w** [comment]
Thanks!
