### ISSUE TITLE
建议出ip版本

### ISSUE THREAD

**Issue by 032** [XIU2/TrackersListCollection#5]
国内可能会遮蔽域名,,根据国情建议出ip版本,像https://github.com/ngosang/trackerslist 这样

**Comment by XIU2** [comment]
这个考虑过，但是有个问题是，我不清楚哪些 Tracker 服务器的服务程序监听了 IP。

因为域名和IP是两个东西，如果服务器上面的 Tracker 服务程序绑定的是域名而没有绑定IP，那就不能单纯的把 域名 替换成 IP 来使用（即无法通过 http://ip:xxx 来访问 Tracker 服务器）。

如果要知道是否可以替换成 IP ，就要一个个的去替换IP后测试 Tracker 可用性，但我的项目只是单纯整合，并没有去测试各个 Tracker 的可用性。

**Comment by 052** [comment]
> 这个考虑过，但是有个问题是，我不清楚哪些 Tracker 服务器的服务程序监听了 IP。
> 
> 因为域名和IP是两个东西，如果服务器上面的 Tracker 服务程序绑定的是域名而没有绑定IP，那就不能单纯的把 域名 替换成 IP 来使用（无法通过 http://ip:xxx 来访问 Tracker 服务器），就像你能访问百度的域名，但是你却不能直接访问百度域名对应的IP（http://x.x.x.x 这样）。
> 
> 如果要知道是否可以替换成 IP ，就要一个个的去替换IP后测试 Tracker 可用性，但我的项目只是单纯整合，并没有去测试各个 Tracker 的可用性。

哦明白了

**Comment by XIU2** [comment]
测试对比了一下，效果并不是很理想。
- 一方面 就像我前面说的那样，有些 Tracker 服务器只监听了域名而没有监听 IP。
- 一方面 凡是 https:// 的域名，都不可能监听 IP，因为用 IP 做主机名的话，SSL 证书只能自签发。
- 一方面 一些 Tracker 使用了 CDN，这种就不可能直接通过 IP 访问。

所以在没有什么好思路前，我不会出 IP 版本的 Tracker List。

**Comment by xdown-org** [comment]
可否添加一个客户端， xdown.org

xdown 支持自定义非53标准端口dns

而且支持 自定义ip

`https://trackerslist.com/all.txt --uri-defined-host-info "185.199.109.153"`

xdown目前还在继续完善中，有什么好建议可以联系 gatebyebye@outlook.com

**Comment by XIU2** [comment]
> 可否添加一个客户端， xdown.org
> 
> xdown 支持自定义非53标准端口dns
> 
> 而且支持 自定义ip
> 
> `https://trackerslist.com/all.txt --uri-defined-host-info "185.199.109.153"`
> 
> xdown目前还在继续完善中，有什么好建议可以联系 [gatebyebye@outlook.com](mailto:gatebyebye@outlook.com)

没明白你说的是什么。。。
我的项目官网是部署在 Github Pages 上面的（网页文件就在该项目中），也就是 Github 的服务器。

**Comment by xdown-org** [comment]
官方bt客户端推荐里面挂一个xdown介绍呀，

xdown可以自定义ip 防止dns污染，

**Comment by xdown-org** [comment]
就像
https://trackerslist.com/#/?id=aria2

这样
来一个 

https://trackerslist.com/#/?id=xdown

**Comment by XIU2** [comment]
> 就像
> https://trackerslist.com/#/?id=aria2
> 
> 这样
> 来一个
> 
> https://trackerslist.com/#/?id=xdown

已添加至末尾，希望不要介意。
https://trackerslist.com/#/?id=xdown
因为 Github CDN 缓存的原因，可能不会立即显示，请等待片刻。

**Comment by xdown-org** [comment]
感谢，

**Comment by renfei** [comment]
确实不能将域名解析成IP，想法虽然好，但后面会有很多问题。
如果简单的将域名解析成IP的话，不仅仅是SSL证书对不上，就算是http的也不行，因为：
我不想暴露我的真实IP地址，我就会套用CDN来隐藏真实地址，这个时候你会解析出一组IP，而这一组IP都不是我的，而是CDN服务器的地址，直接使用IP是没用的。而且一个服务器上可能有很多服务，我也会使用Nginx反代，而区别各个服务就是靠域名host来区分的。
可能他的需求是将域名和IP的列表分开发布？

![image](https://user-images.githubusercontent.com/6532952/104688469-c5506780-573b-11eb-9453-b13451733b96.png)

![image](https://user-images.githubusercontent.com/6532952/104688450-b8cc0f00-573b-11eb-8165-1e22dbcab2e6.png)

**Comment by liuxi378** [comment]
你好，关于Aria2的tracker地址已经打不开了，还请百忙之中抽出点时间处理下，谢谢

**Comment by XIU2** [comment]
@liuxi378 可以打开呀，你打不开提示什么？你是什么运营商？移动么？（移动的蔷中蔷比较出名~

我已经添加了 Aria2 的备用地址。

**Comment by AlexanderMC8533** [comment]
用的很正常












Taleling
***@***.***

FutureLand&nbsp;Create&amp;Design&nbsp;Corp.
首席执行官

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月20日(周五) 凌晨0:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [XIU2/TrackersListCollection] 建议出ip版本 (#5)




 
你好，关于Aria2的tracker地址已经打不开了，还请百忙之中抽出点时间处理下，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuxi833** [comment]
> @liuxi378可以打开呀，你打不开提示什么？你是什么运营商？移动么？（移动的蔷中蔷比较出名~
> 
> 我已经添加了 Aria2 的备用地址。
![QQ截图20210820150547](https://user-images.githubusercontent.com/76251211/130194043-19fad32b-e2b0-4f39-8a34-98f49779bacc.png)
我是移动的宽带，有科学上网，之前一直都是能打开的，就最近这几天打不开了
![1](https://user-images.githubusercontent.com/76251211/130194286-5fe5941d-b711-4c66-8697-bbfebd49f8c4.png)

**Comment by XIU2** [comment]
@liuxi833 移动的话正常，不稀奇~
移动自己有个**黑名单系统**，很多国外网站都被陆续屏蔽了，不同地区的黑名单系统都是**独立**的（因此只局限于一地，而不是全国），可能是你的当地移动前段时间将该域名加到自己的黑名单中了。

我去找了个在线网站测速的网站测了下，确实**个别地区**的**移动**无法访问。其他运营商都正常。

**Comment by f4nff** [comment]
```
curl https://trackerslist.com/all.txt -k
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to trackerslist.com:443
```

准备弃用了，ip都连不上，0成本的运营，体验差到极点。

**Comment by XIU2** [comment]
@f4nff 最近部分地区的移动运营商屏蔽了我的域名（移动墙中墙），这个无解。
我提供的有备用地址：
https://cdn.jsdelivr.net/gh/XIU2/TrackersListCollection@master/all.txt

**Comment by f4nff** [comment]
https://newtrackon.com/api/stable

换这个了，
https://trackerslist.com/all.txt 

太多无效tracker，导致请求耗费大量无用资源，而且也不去验证有效性。

**Comment by XIU2** [comment]
@f4nff 我的列表中已经包含你说的这个项目。

验证有效性确实是个麻烦的事情，起初我也只是自用的，谁知道用的人越来越多了。。。
后来我又折腾了下验证方案，过滤掉了不少失效的 Tracker 地址，后续每次更新都会过滤掉几百个失效的。

> 你也知道，我这个项目其实就是对网上热门的一些 Tracker 列表项目进行整合、过滤，这些列表加在一起后我这边筛选过滤一遍后，就能过滤出**几百个无效**的 Tracker 地址，着实水分也很大。。。
> 另外我是用国外服务器整合、过滤、筛选的，因此也有部分**域名被国内被封**的 Tracker 地址没有被过滤掉。

我也曾经尝试过使用 newtrackon 这网站所用的开源检测项目去过滤，结果发现也存在很多缺陷，折腾来折腾去也没有找到更好的方案，不过实际上对 BT 软件而言，资源消耗影响很小的，毕竟才两三百个 Tracker 地址罢了，这要也能卡那就真的是。。。

总之，相比这点感受不到的资源消耗影响，多一些 Tracker 就会**多一些找到更多用户的可能**~
找到的用户越多，下载速度才会越快，所以我一直推荐使用的是完整列表。

**Comment by yeezylife** [comment]
你的上游里有几个列表是自带IP版本的,把他们的IP版本合在一起不就可以了(没有IP版本的上游不合),这样就不用验证了,因为上游验证过的.
