### ISSUE TITLE
请求添加 TrackersList(http://open.acgtracker.com:1096/announce)

### ISSUE THREAD

**Issue by SanTTang** [XIU2/TrackersListCollection#50]
tracker 来源地址：https://acgtracker.com/
tarckerlist：
http://open.acgtracker.com:1096/announce

动漫资源上有覆盖。

**Comment by XIU2** [comment]
本项目主要是对其他 Tracker 列表进行整合过滤，一般不会单独添加某个 Tracker 地址。

建议提交至：
- https://github.com/ngosang/trackerslist （Issues 提交）
- https://newtrackon.com （自助提交）

只要它们任意一个收录该 Tracker 地址了，我这边也会同步更新~
