### ISSUE TITLE
Invalid tracker in all.txt

### ISSUE THREAD

**Issue by liurui39660** [XIU2/TrackersListCollection#56]
https://github.com/XIU2/TrackersListCollection/blob/1e31f7e0955e4f813fa3e6b0d424c275cd772e98/all.txt#L235

This invalid tracker will cause qBittorent web UI malfunctions. Please remove it.

**Comment by XIU2** [comment]
Ok, this error has been removed.
And updated the filtering mechanism, this kind of problem should not appear in the future...
