### ISSUE TITLE
Add new tracker

### ISSUE THREAD

**Issue by owner** [XIU2/TrackersListCollection#6]
```
        * HTTP: http://tracker.darli.net:6611/announce
	* UDP: udp://tracker.darli.net:6611
	* WS: ws://tracker.darli.net:6611
```

**Comment by XIU2** [comment]
Sorry, this project only integrates the Tracker project and does not strictly maintain each Tracker server. If you need to add, ***please submit Tracker to the following projects:***

- https://github.com/ngosang/trackerslist
- https://newtrackon.com/list
- https://torrents.io/tracker-list/
- http://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt
- https://tinytorrent.net/best-torrent-tracker-list-updated/
- https://torrenttrackerss.com/torrent-tracker-list/
- http://www.torrenttrackerlist.com/torrent-tracker-list
