### ISSUE TITLE
怎么检测服务器状态的？

### ISSUE THREAD

**Issue by xin-u** [XIU2/TrackersListCollection#62]
我观察到 [newTrackon.com ](https://newTrackon.com)上有不少连接速度和存活状态都不错的服务器，（禁ICMP）没有进入到此列表。但此列表中有大量无效地址。

**Comment by XIU2** [comment]
all.txt 中收录了 https://newtrackon.com/api/stable
best.txt 中收录了 https://newtrackon.com/api/99
检测所有域名是否正常解析 IP，以及所有 HTTP/S 协议 Tracker 的端口连通性。

**Comment by XIU2** [comment]
起初只是自用，没想到不知不觉就这么多人用了。。。
因为没找到好用合适的批量检测 Tracker 的工具（包括 newTrackon 那个开源项目我也试过，但是其对 UDP 协议的 Tracker 检测存在一些问题），所以现在还一直延续着比较简单粗暴的过滤机制。

**Comment by XIU2** [comment]
刚才看了下，发现本项目 Tracker 数量好像少了很多，有点奇怪，测试了下发现前段时间我的某次改动（为了修复一个问题，竟然又特么创造出来一个问题），导致有不少正常的 Tracker 给漏掉了。。。
折腾了下，已经给修复了~

这段时间都没怎么关注这个项目，没有第一时间发现这个问题。

**Comment by xin-u** [comment]
@XIU2 我在家用Docker搭建了个[newTrackon](https://github.com/CorralPeltzer/newTrackon)，应该可以用哦！这样的数据应该比从别人那里抓取数据更准确。不知道你说的UDP问题是什么。

我觉得用中国的服务器搭建一个检查节点更适合这个项目的目的。服务要有IPv6、v4才行

![网页捕获_7-11-2021_194428_192 168 3 29](https://user-images.githubusercontent.com/76462613/140643635-477a5aa1-ccc0-4cf6-a1b2-888ad4970318.jpeg)

**Comment by xin-u** [comment]
![网页捕获_7-11-2021_194428_192 168 3 29](https://user-images.githubusercontent.com/76462613/140643635-477a5aa1-ccc0-4cf6-a1b2-888ad4970318.jpeg)

**Comment by XIU2** [comment]
我没有国内服务器，国内服务器也不便宜呀，这个项目目前是运行在我的国外服务器上面的。

**Comment by xin-u** [comment]
> 我没有国内服务器，国内服务器也不便宜呀，这个项目目前是运行在我的国外服务器上面的（连服务器也是朋友送的，我的各种项目都在上面跑）。

现在腾讯、阿里的轻量应用服务器只要48一年。三年才一百多，只是没有IPv6

**Comment by XIU2** [comment]
没有购买的欲望~
除了这个项目外，我其他的所有自用/开源项目都用不上国内服务器，太浪费啦。

虽然这个项目光买个域名就已经六七十/年了~
公益项目懒得投入这些成本。

**Comment by XIU2** [comment]
我之所以从别人项目中抓取，而不是自己收集、接收他人提交、整理，就是为了**省力**。

就像我前面说的，这项目起初只是我自用的，一开始比现在还粗糙，起码后来我特地加了一些过滤机制。
毕竟对于我来说，这只是一个业余自用的项目罢了（虽然用的人多了点），但是我个人很懒，不想投入过多的精力去维护该项目，平时也不怎么关注，都是挂服务器上面每天定时跑脚本更新的。

适量的无效 Tracker 我是可以接受的，反正 BT 软件都会自己过滤的，毕竟就算该项目过滤的再准确，**实际使用也感觉不出来**（除非有强迫症一直盯着 Tracker 工作状态），毕竟对 BT 软件来说这点数量只是毛毛雨~

**Comment by xin-u** [comment]
只跑个定时脚本就不需要服务器啦，在这个仓库里上传脚本代码，点点鼠标启用 GitHub actions 足够了~ 我的好几个项目都这样跑的（免运维、不操心

国内的免费替代产品有 腾讯Coding、阿里云效....
