### ISSUE TITLE
为啥这些磁力下载不了呢？

### ISSUE THREAD

**Issue by jcyhcs** [XIU2/TrackersListCollection#63]
hi，大佬：
我用了您的便携版4.3.9.10，我用一个网站的资源测试了一下：
http://www.mzzfree.com/news/show.php?itemid=705
但是，几个小时过去了，一点速度没有：
![image](https://user-images.githubusercontent.com/34532224/141711265-b8dbf53d-4eeb-4927-a357-1b231828f368.png)
您能解释一下原理和原因吗？
我没有公网ip

**Comment by XIU2** [comment]
BT 下载没速度大都是因为**资源冷门**导致的。

**_BT 下载的文件都是别人上传给你的。
BT 下载速度就是别人下载速度总和。_**

因此链接到的做种上传用户越多，下载速度就越快。
反之，用户越少速度就越慢，如果找不到用户或太少就等于死种了，无法下载，无解！

在你提供的图片里可以看到，这两个资源，只找到了 `个位数` 的用户，其中正在做种上传的用户更是只有 ` 1 ` 个，甚至就这 1 个人你也**没连上**（括号里面是总数，外面是已连接的数量）。
这怎么可能会有速度，你总不能**凭空下载文件**吧？

DHT、Peer、Tracker 都是用来寻找更多用户的，找到的用户越多，自然就会提高下载速度。
但它们并不是万能的，如果这个资源本身就很冷门，那么也不可能凭空制造用户向你上传。

BT 只适合用来下载热门资源，即近期发布的资源，对于已经冷掉的资源，请寻找其他方式下载吧（如网盘）。
