### ISSUE TITLE
中国可用的 BT Tracker 服务器列表，每24小时自动更新和tracker服务器列表 2017~2022  这两个好像没有的，可以加上

### ISSUE THREAD

**Issue by a201500** [XIU2/TrackersListCollection#66]
中国可用的 BT Tracker 服务器列表，每24小时自动更新：https://www.yaozuopan.top/index.php/archives/1014/
tracker服务器列表 2017~2022：https://www.cnblogs.com/qiufen/p/15358623.html
麻烦看下有没有这两个，没有的话可以加上这两个来源

**Comment by XIU2** [comment]
曾经加过，但是被反应质量不佳就给撤掉了。。。
