### ISSUE TITLE
格式错乱了

### ISSUE THREAD

**Issue by fengmlo** [XIU2/TrackersListCollection#7]
</head>

	</script>

	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

	<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css'>

	<link rel="icon" type="image/png" href="https://torrents.io/theme/assets/img/favicon.png">

	<link rel="search" type="application/opensearchdescription+xml" title="Torrents Search" href="/opensearch.xml"/>

	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Torrent Search</title>

	ga('send', 'event', 'Search', 'search', $(".nav-search-input").val() );

	text-decoration: line-through;

	var ajaxurl = "https://torrents.io/ajax.php";

	var searchUrl = "https://search.torrents.io";

	var siteurl = "https://torrents.io";

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),

1337x              </a>

<!DOCTYPE html>

</body>

</div>

</div>

</div>

</div>

</div>

</div>

</div>

</div>

</div>

</fieldset>

</form>

</html>

</li>

</script>

</ul>

<a href="#" title="" class="scroll-left"><i class="fa fa-angle-right" aria-hidden="true"></i></a>

<a href="#" title="" class="scroll-right"><i class="fa fa-angle-left" aria-hidden="true"></i></a>

<a href="https://search.torrents.io/It s a Wonderful Life:1337x" id="273" title="Search torrents on 1337x"

<a href="https://search.torrents.io/It s a Wonderful Life:limetorrents" id="1099" title="Search torrents on LimeTorrents"

<a href="https://search.torrents.io/It s a Wonderful Life:pirate-bay" id="9" title="Search torrents on Pirate Bay"

<a href="https://search.torrents.io/It s a Wonderful Life:rarbg" id="127" title="Search torrents on RARBG"

<a href="https://search.torrents.io/It s a Wonderful Life:torrent-downloads" id="1301" title="Search torrents on Torrent Downloads"

<a href="https://search.torrents.io/It s a Wonderful Life:torrentseeker" id="2268" title="Search torrents on Torrentseeker"

<a href="https://search.torrents.io/It s a Wonderful Life:torrentz2" id="2530" title="Search torrents on Torrentz2"

<a href="https://search.torrents.io/It s a Wonderful Life:zooqle" id="2548" title="Search torrents on Zooqle"

<a href="https://torrents.io/settings/" rel="nofollow" onclick="ga('send', 'event', 'Feature', 'click', 'Search settings link');">Customize Search Sites</a>

<body>

<button type="reset" class="clear-search-input" style="display:none !important;"><i class="fa fa-times"></i></button><button type="submit" class="btn-submit-search"><i class="fa fa-search"></i></button>

<div class="form-wrap">

<div class="large-4 show-for-large-up columns">

<div class="logo-s"><a href="https://torrents.io"><img src="https://torrents.io/theme/assets/img/logo-s.png" alt="torrents" /></a></div>

<div class="nav-fill">

<div class="nav-right">

<div class="nav-search-field"><input type="text" class="nav-search-input" value="It s a Wonderful Life" /></div>

<div class="nav-search-submit">

<div class="row">

<div class="s-form">

<div class="s-options">

<div class="s-sites">

<div class="scroll-btns invisible" style="float:right">

<div class="search-options">

<div class="search-panel">

<div class="small-12 large-8 columns">

<div class="switch-wrapper">

<div class="target-site">

<fieldset class="switch" tabindex="0">

<form method="POST" action="https://search.torrents.io/It s a Wonderful Life:" class="nav-search-form">

<head>

<html lang="en">

<iframe class="target-site-frame" src="https://torrentseeker.com/search.php?q=It s a Wonderful Life"></iframe>

<input id="toggle-site-proxy" type="checkbox"  onclick="ga('send', 'event', 'Feature', 'click', 'Proxy on-off');">

<label for="toggle-site-proxy"></label>

<li class="add-more-link"><a href="https://torrents.io/settings/" rel="nofollow" onclick="ga('send', 'event', 'Feature', 'click', 'Add torrent sites');">Add torrent sites</a></li>

<li class="search-site ">

<li class="search-site site-selected">

<link rel='dns-prefetch' href='//s.w.org' />

<link rel='stylesheet' id='category-css'  href='https://torrents.io/theme/assets/css/category.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='das-css'  href='https://torrents.io/theme/assets/css/das.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='fdn-css'  href='https://torrents.io/theme/assets/css/fdn.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='frontpage-css'  href='https://torrents.io/theme/assets/css/frontpage.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='global-css'  href='https://torrents.io/theme/assets/css/global.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='head-foot-css'  href='https://torrents.io/theme/assets/css/head-foot.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='normalize-css'  href='https://torrents.io/theme/assets/css/normalize.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='pages-css'  href='https://torrents.io/theme/assets/css/pages.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='sbasic-css'  href='https://torrents.io/theme/assets/css/sbasic.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='search-css'  href='https://torrents.io/theme/assets/css/search.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='settings-css'  href='https://torrents.io/theme/assets/css/settings.css?ver=5.2.4' type='text/css' media='all' />

<link rel='stylesheet' id='sites-css'  href='https://torrents.io/theme/assets/css/sites.css?ver=5.2.4' type='text/css' media='all' />

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>

<script src="https://torrents.io/theme/assets/js/foundation.min.js"></script>

<script src="https://torrents.io/theme/assets/js/foundation.tab.js"></script>

<script src="https://torrents.io/theme/assets/js/jquery-ui.min.js"></script>

<script src="https://torrents.io/theme/assets/js/script.js"></script>

<script type="text/javascript">$(document).foundation();</script>

<script>

<span class="spinner" style="float:left"></span>

<span>Proxy</span>

<style type="text/css">.broken_link, a.broken_link {

<ul class="search-sites">

LimeTorrents              </a>

Pirate Bay              </a>

RARBG              </a>

Torrent Downloads              </a>

Torrentseeker              </a>

Torrentz2              </a>

Zooqle              </a>

data-name="1337x" data-proxy="https://1337x.is" data-url="https://1337x.to" data-search-url="srch?search=@@s@@" rel="nofollow">

data-name="limetorrents" data-proxy="https://limetorrents.unblockit.ca" data-url="https://www.limetorrents.info" data-search-url="search/all/@@s@@/" rel="nofollow">

data-name="pirate-bay" data-proxy="https://pirateproxy.lat" data-url="https://pirateproxy.cam" data-search-url="search/@@s@@" rel="nofollow">

data-name="rarbg" data-proxy="https://rarbgmirror.com" data-url="https://rarbg.to" data-search-url="torrents.php?search=@@s@@" rel="nofollow">

data-name="torrent-downloads" data-proxy="https://torrentdownloads.unblocked.win" data-url="https://torrentdownloads.me" data-search-url="search/?search=@@s@@" rel="nofollow">

data-name="torrentseeker" data-proxy="" data-url="https://torrentseeker.com" data-search-url="search.php?q=@@s@@" rel="nofollow">

data-name="torrentz2" data-proxy="https://torrentz2.is" data-url="https://torrentz2.eu" data-search-url="search?f=@@s@@" rel="nofollow">

data-name="zooqle" data-proxy="https://zooqle.unblocked.win" data-url="https://zooqle.com/" data-search-url="search?q=@@s@@" rel="nofollow">

ga('create', 'UA-137843655-1', 'auto');

ga('create', 'UA-91357-1', 'auto');

ga('send', 'pageview');

http://0d.kebhana.mx:443/announce

http://104.238.198.186:8000/announce

http://104.28.1.30:8080/announce

http://104.28.16.69/announce

http://107.150.14.110:6969/announce

http://109.121.134.121:1337/announce

http://114.55.113.60:6969/announce

http://125.227.35.196:6969/announce

http://128.199.70.66:5944/announce

http://157.7.202.64:8080/announce

http://158.69.146.212:7777/announce

http://173.254.204.71:1096/announce

http://178.175.143.27/announce

http://178.33.73.26:2710/announce

http://182.176.139.129:6969/announce

http://185.5.97.139:8089/announce

http://185.83.215.123:6969/announce

http://188.165.253.109:1337/announce

http://194.106.216.222/announce

http://195.123.209.37:1337/announce

http://198.177.123.164/announce

http://210.244.71.25:6969/announce

http://210.244.71.26:6969/announce

http://213.163.67.56:1337/announce

http://37.19.5.139:6969/announce

http://37.19.5.155:6881/announce

http://46.4.109.148:6969/announce

http://5.2.79.22:6969/announce

http://5.79.249.77:6969/announce

http://5.79.83.193:2710/announce

http://51.254.244.161:6969/announce

http://52.28.76.37:6969/announce

http://52.29.11.73:6969/announce

http://52.58.128.163:6969/announce

http://59.36.96.77:6969/announce

http://62.210.202.61/announce

http://74.82.52.209:6969/announce

http://78.30.254.12:2710/announce

http://80.246.243.18:6969/announce

http://81.200.2.231/announce

http://85.17.19.180/announce

http://87.110.238.140:6969/announce

http://87.248.186.252:8080/announce

http://87.253.152.137/announce

http://91.216.110.47/announce

http://91.217.91.21:3218/announce

http://91.218.230.81:6969/announce

http://93.92.64.5/announce

http://95.211.168.204:2710/announce

http://[2001:19f0:6c01:1b7d:5400:1ff:fefc:3c2a]:6969/announce

http://[2001:1af8:4700:a032:1234::]:6969/announce

http://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce

http://[2001:41d0:305:2100::16a3]:6969/announce

http://[2001:470:1:189:0:1:2:3]:6969/announce

http://[2a02:c205:2026:1682::1]:443/announce

http://[2a04:ac00:1:3dd8::1:2710]:2710/announce

http://acg.rip:6699/announce

http://agusiq-torrents.pl:6969/announce

http://asnet.pw:2710/announce

http://bigfoot1942.sektori.org:6969/announce

http://bt.henbt.com:2710/announce

http://bt.pusacg.org:8080/announce

http://bt.xxx-tracker.com:2710/announce

http://bt2.careland.com.cn:6969/announce

http://carapax.net:6969/announce

http://denis.stalker.upeer.me:6969/announce

http://explodie.org:6969/announce

http://fxtt.ru:80/announce

http://grifon.info:80/announce

http://h4.trakx.nibba.trade:80/announce

http://mail2.zelenaya.net:80/announce

http://mgtracker.org:2710/announce

http://mgtracker.org:6969/announce

http://ns349743.ip-91-121-106.eu:80/announce

http://open.acgnxtracker.com:80/announce

http://open.acgtracker.com:1096/announce

http://open.lolicon.eu:7777/announce

http://open.touki.ru/announce.php

http://opentracker.i2p.rocks:6969/announce

http://p4p.arenabg.ch:1337/announce

http://p4p.arenabg.com:1337/announce

http://pow7.com:80/announce

http://pt.lax.mx:80/announce

http://retracker.bashtel.ru:80/announce

http://retracker.hotplug.ru:2710/announce

http://retracker.krs-ix.ru:80/announce

http://retracker.mgts.by:80/announce

http://retracker.sevstar.net:2710/announce

http://retracker.spark-rostov.ru:80/announce

http://retracker.telecom.by:80/announce

http://share.camoe.cn:8080/announce

http://t.acg.rip:6699/announce

http://t.nyaatracker.com:80/announce

http://thetracker.org:80/announce

http://torrentclub.tech:6969/announce

http://torrentsmd.com:8080/announce

http://torrentsmd.eu:8080/announce

http://torrentsmd.me:8080/announce

http://tr.cili001.com:8070/announce

http://tr.kxmp.cf:80/announce

http://tracker.aletorrenty.pl:2710/announce

http://tracker.baravik.org:6970/announce

http://tracker.beeimg.com:6969/announce

http://tracker.birkenwald.de:6969/announce

http://tracker.bittor.pw:1337/announce

http://tracker.bt4g.com:2095/announce

http://tracker.bz:80/announce

http://tracker.calculate.ru:6969/announce

http://tracker.city9x.com:2710/announce

http://tracker.corpscorp.online:80/announce

http://tracker.devil-torrents.pl:80/announce

http://tracker.dler.org:6969/announce

http://tracker.dutchtracking.com:80/announce

http://tracker.dutchtracking.nl:80/announce

http://tracker.edoardocolombo.eu:6969/announce

http://tracker.electro-torrent.pl:80/announce

http://tracker.ex.ua:80/announce

http://tracker.filemail.com:6969/announce

http://tracker.filepit.to:6969/announce

http://tracker.files.fm:6969/announce

http://tracker.filetracker.pl:8089/announce

http://tracker.flashtorrents.org:6969/announce

http://tracker.gbitt.info:80/announce

http://tracker.grepler.com:6969/announce

http://tracker.internetwarriors.net:1337/announce

http://tracker.ipv6tracker.ru:80/announce

http://tracker.kamigami.org:2710/announce

http://tracker.kicks-ass.net:80/announce

http://tracker.kuroy.me:5944/announce

http://tracker.lelux.fi:80/announce

http://tracker.mg64.net:6881/announce

http://tracker.moeking.me:6969/announce

http://tracker.novg.net:6969/announce

http://tracker.nyaa.uk:6969/announce

http://tracker.nyap2p.com:8080/announce

http://tracker.opentrackr.org:1337/announce

http://tracker.port443.xyz:6969/announce

http://tracker.skyts.net:6969/announce

http://tracker.tfile.co:80/announce

http://tracker.tfile.me:80/announce

http://tracker.tiny-vps.com:6969/announce

http://tracker.torrentbay.to:6969/announce

http://tracker.torrentyorg.pl:80/announce

http://tracker.trackerfix.com:80/announce

http://tracker.tvunderground.org.ru:3218/announce

http://tracker.uw0.xyz:6969/announce

http://tracker.ygsub.com:6969/announce

http://tracker.yoshi210.com:6969/announce

http://tracker01.loveapp.com:6789/announce

http://tracker1.itzmx.com:8080/announce

http://tracker1.wasabii.com.tw:6969/announce

http://tracker2.itzmx.com:6961/announce

http://tracker2.wasabii.com.tw:6969/announce

http://tracker3.itzmx.com:6961/announce

http://tracker4.emce.org:12345/announce

http://tracker4.itzmx.com:2710/announce

http://vps02.net.orel.ru:80/announce

http://www.loushao.net:8080/announce

http://www.proxmox.com:6969/announce

http://www.wareztorrent.com:80/announce

https://104.28.17.69/announce

https://1337.abcvg.info:443/announce

https://open.kickasstracker.com:443/announce

https://t.quic.ws:443/announce

https://tracker.bt-hash.com:443/announce

https://tracker.fastdownload.xyz:443/announce

https://tracker.gbitt.info:443/announce

https://tracker.nanoha.org:443/announce

https://tracker.opentracker.se:443/announce

https://tracker.sloppyta.co:443/announce

https://tracker.vectahosting.eu:2053/announce

if ( $(".nav-search-input").val() != "" ) {

m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)

udp://104.238.198.186:8000/announce

udp://107.150.14.110:6969/announce

udp://109.121.134.121:1337/announce

udp://114.55.113.60:6969/announce

udp://128.199.70.66:5944/announce

udp://151.80.120.114:2710/announce

udp://168.235.67.63:6969/announce

udp://178.33.73.26:2710/announce

udp://182.176.139.129:6969/announce

udp://185.225.17.100:1337/announce

udp://185.5.97.139:8089/announce

udp://185.83.215.123:6969/announce

udp://185.86.149.205:1337/announce

udp://188.165.253.109:1337/announce

udp://191.101.229.236:1337/announce

udp://194.106.216.222:80/announce

udp://195.123.209.37:1337/announce

udp://195.123.209.40:80/announce

udp://208.67.16.113:8000/announce

udp://212.1.226.176:2710/announce

udp://212.47.227.58:6969/announce

udp://213.163.67.56:1337/announce

udp://37.19.5.155:2710/announce

udp://45.56.74.11:6969/announce

udp://46.4.109.148:6969/announce

udp://5.2.79.22:6969/announce

udp://5.79.249.77:6969/announce

udp://5.79.83.193:6969/announce

udp://51.254.244.161:6969/announce

udp://52.28.76.37:6969/announce

udp://52.29.11.73:6969/announce

udp://52.58.128.163:6969/announce

udp://62.138.0.158:6969/announce

udp://62.212.85.66:2710/announce

udp://74.82.52.209:6969/announce

udp://78.30.254.12:2710/announce

udp://85.17.19.180:80/announce

udp://89.234.156.205:80/announce

udp://9.rarbg.com:2710/announce

udp://9.rarbg.me:2710/announce

udp://9.rarbg.me:2780/announce

udp://9.rarbg.to:2710/announce

udp://9.rarbg.to:2730/announce

udp://91.216.110.52:451/announce

udp://91.218.230.81:6969/announce

udp://94.23.183.33:6969/announce

udp://95.211.168.204:2710/announce

udp://[2001:19f0:6c01:1b7d:5400:1ff:fefc:3c2a]:6969/announce

udp://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce

udp://[2001:41d0:305:2100::16a3]:6969/announce

udp://[2001:470:1:189:0:1:2:3]:6969/announce

udp://[2a03:2c40:10:2163::1]:6969/announce

udp://[2a03:7220:8083:cd00::1]:451/announce

udp://[2a04:ac00:1:3dd8::1:2710]:2710/announce

udp://[2a04:c44:e00:32e0:4cf:6aff:fe00:aa1]:6969/announce

udp://bigfoot1942.sektori.org:6969/announce

udp://bt.aoeex.com:8000/announce

udp://bt.okmp3.ru:2710/announce

udp://bt.xxx-tracker.com:2710/announce

udp://bt1.archive.org:6969/announce

udp://bt2.54new.com:8080/announce

udp://bt2.archive.org:6969/announce

udp://carapax.net:6969/announce

udp://chihaya.toss.li:9696/announce

udp://contrata.putasysexo.com:53/announce

udp://denis.stalker.upeer.me:6969/announce

udp://eddie4.nl:6969/announce

udp://exodus.desync.com:6969/announce

udp://home.penza.com.ru:6969/announce

udp://inferno.demonoid.pw:3418/announce

udp://ipv4.tracker.harry.lu:80/announce

udp://ipv6.tracker.harry.lu:80/announce

udp://mgtracker.org:2710/announce

udp://open.demonii.com:1337

udp://open.demonii.si:1337/announce

udp://open.nyap2p.com:6969/announce

udp://open.stealth.si:80/announce

udp://opentor.org:2710/announce

udp://opentracker.i2p.rocks:6969/announce

udp://peerfect.org:6969/announce

udp://public.popcorn-tracker.org:6969/announce

udp://pubt.in:2710/announce

udp://qg.lorzl.gq:2710/announce

udp://retracker.akado-ural.ru:80/announce

udp://retracker.baikal-telecom.net:2710/announce

udp://retracker.hotplug.ru:2710/announce

udp://retracker.lanta-net.ru:2710/announce

udp://retracker.netbynet.ru:2710/announce

udp://retracker.nts.su:2710/announce

udp://retracker.sevstar.net:2710/announce

udp://santost12.xyz:6969/announce

udp://shadowshq.eddie4.nl:6969/announce

udp://shadowshq.yi.org:6969/announce

udp://tc.animereactor.ru:8082/announce

udp://thetracker.org:80/announce

udp://torrent.gresille.org:80/announce

udp://torrentclub.tech:6969/announce

udp://tr.bangumi.moe:6969/announce

udp://tr.cili001.com:8070/announce

udp://tracker-udp.gbitt.info:80/announce

udp://tracker.0o.is:6969/announce

udp://tracker.aletorrenty.pl:2710/announce

udp://tracker.beeimg.com:6969/announce

udp://tracker.birkenwald.de:6969/announce

udp://tracker.bittor.pw:1337/announce

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.cyberia.is:6969/announce

udp://tracker.cypherpunks.ru:6969/announce

udp://tracker.dler.org:6969/announce

udp://tracker.doko.moe:6969/announce

udp://tracker.ds.is:6969/announce

udp://tracker.dutchtracking.com:6969/announce

udp://tracker.dyn.im:6969/announce

udp://tracker.eddie4.nl:6969/announce

udp://tracker.ex.ua:80/announce

udp://tracker.filemail.com:6969/announce

udp://tracker.filepit.to:6969/announce

udp://tracker.filetracker.pl:8089/announce

udp://tracker.flashtorrents.org:6969/announce

udp://tracker.grepler.com:6969/announce

udp://tracker.halfchub.club:6969/announce

udp://tracker.iamhansen.xyz:2000/announce

udp://tracker.ilibr.org:80/announce

udp://tracker.internetwarriors.net:1337/announce

udp://tracker.justseed.it:1337/announce

udp://tracker.kamigami.org:2710/announce

udp://tracker.kicks-ass.net:80/announce

udp://tracker.kuroy.me:5944/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://tracker.lelux.fi:6969/announce

udp://tracker.mg64.net:2710/announce

udp://tracker.mg64.net:6969/announce

udp://tracker.moeking.me:6969/announce

udp://tracker.msm8916.com:6969/announce

udp://tracker.nextrp.ru:6969/announce

udp://tracker.novg.net:6969/announce

udp://tracker.nyaa.uk:6969/announce

udp://tracker.open-internet.nl:6969/announce

udp://tracker.openbittorrent.com:80/announce

udp://tracker.opentrackr.org:1337/announce

udp://tracker.piratepublic.com:1337/announce

udp://tracker.port443.xyz:6969/announce

udp://tracker.sbsub.com:2710/announce

udp://tracker.skyts.net:6969/announce

udp://tracker.supertracker.net:1337/announce

udp://tracker.swateam.org.uk:2710/announce

udp://tracker.tiny-vps.com:6969/announce

udp://tracker.torrent.eu.org:451/announce

udp://tracker.torrentbay.to:6969/announce

udp://tracker.trackton.ga:7070/announce

udp://tracker.tvunderground.org.ru:3218/announce

udp://tracker.uw0.xyz:6969/announce

udp://tracker.vanitycore.co:6969/announce

udp://tracker.yoshi210.com:6969/announce

udp://tracker.zum.bi:6969/announce

udp://tracker1.itzmx.com:8080/announce

udp://tracker2.christianbro.pw:6969/announce

udp://tracker2.indowebster.com:6969/announce

udp://tracker2.itzmx.com:6961/announce

udp://tracker3.itzmx.com:6961/announce

udp://tracker4.itzmx.com:2710/announce

udp://tracker4.piratux.com:6969/announce

udp://valakas.rollo.dnsabr.com:2710/announce

udp://wambo.club:1337/announce

udp://xxxtor.com:2710/announce

udp://zephir.monocul.us:6969/announce

udp://zer0day.ch:1337/announce

udp://zer0day.to:1337/announce

wss://tracker.btorrent.xyz

wss://tracker.fastcast.nz

wss://tracker.openwebtorrent.com

}

})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

}</style>	<meta name="robots" content="noindex,nofollow">	<script type="text/javascript">

**Comment by XIU2** [comment]
是 https://torrents.io/tracker-list/ 这个 Tracker 源的问题。
应该是网页改变了，导致我的爬虫爬取错误。
我以及删除这个 Tracker 源，已经恢复了，我稍后看看具体是怎么回事。

**Comment by XIU2** [comment]
简单排查后，应该是今天项目更新时 torrents.io 网站出现短暂的错误，导致 Tracker 获取失败。

为了避免以后再出现这类情况，我已经更新了爬虫，遇到错误会自动终止项目更新行为并通知我。
