### ISSUE TITLE
Request to add TrackersList(Source)

### ISSUE THREAD

**Issue by andy539** [XIU2/TrackersListCollection#71]
Hope to add these TrackersList:
udp://tracker.srv00.com:6969/announce

**Comment by XIU2** [comment]
Sorry, the purpose of this project is to integrate other Trackers List projects, **and not strictly maintain each Tracker.**

**please submit Tracker to the following projects:**

* https://github.com/ngosang/trackerslist
* https://newtrackon.com/
(The website supports automatic submission.)
