### ISSUE TITLE
Request to add software

### ISSUE THREAD

**Issue by filecxx** [XIU2/TrackersListCollection#74]
Hope to add these TrackersList:

File centipede is a brand new download manager software if you could add it to your site list or somewhere else, I will be very grateful. 

thank you.

website is:
http://www.filecxx.com/

https://github.com/filecxx/FileCentipede

**Comment by XIU2** [comment]
Does the software support the use of **Trackers list URL**?
If it's not supported, I won't add it to the README.

**Comment by filecxx** [comment]
![image](https://user-images.githubusercontent.com/100348948/157374527-cce537f5-1335-44ff-8f69-f413756a2909.png)

![image](https://user-images.githubusercontent.com/100348948/157374576-339df927-f66f-441c-8138-d5fde890c2d5.png)

**Comment by XIU2** [comment]
added.
As is customary, I append it to the end.

Github Pages take some time to update (cache).
