### ISSUE TITLE
疑似有tracker返回假数据

### ISSUE THREAD

**Issue by so1ar** [XIU2/TrackersListCollection#76]
http://pow7.com:80/announce

这个tracker无论是下载什么种子，即使是非常冷门的种子，都会返回有420个连接，当然这些连接是假的，根本没有速度，而且在消息栏中还有"Glory to Ukraine!"的字样，怀疑这个tracker的提供者动机不纯
![1648207954_grim](https://user-images.githubusercontent.com/54471528/160114676-38b5ac42-45f2-452d-9b12-5617eb59c541.png)

**Comment by XIU2** [comment]
OK，我已经将其加入黑名单了，下次自动更新时（0 点）就会排除掉~
