### ISSUE TITLE
如何配合磁力magnet链接使用？

### ISSUE THREAD

**Issue by sjtuross** [XIU2/TrackersListCollection#79]
查阅了一下，magnet磁力链接要拼接&tr=来添加tracker，而且url还要encode，批量添加不是很方便，请问有什么好的方法？

**Comment by XIU2** [comment]
你是要发布、分享磁力链接时添加上 Tracker 的么？
毕竟普通用户只是下载的话，是没有这个需求的。

**Comment by sjtuross** [comment]
感谢回复！我不是要发布，我作为普通用户打算下载下面这个片子，你可以发现里面就一个tracker，URL decode之后是`tr=http://bt4.t-ru.org/ann?magnet`我想加你提供的tracker，不知是否可行？

```
magnet:?xt=urn:btih:46BB8E54862086CD7C85DB33DE7F5BC27A16266E&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=Безумный%20Макс%3A%20Дорога%20ярости%20%2F%20Mad%20Max%3A%20Fury%20Road%20%28Джордж%20Миллер%2FGeorge%20Miller%29%20%5B2015%2C%20Австралия%2C%20США%2C%20боевик%2C%20фантастика%2C%20приключения%2C%20UHD%20BDRemux%2021
```

**Comment by XIU2** [comment]
你为什么不直接加到 BT 软件中。。。

**Comment by sjtuross** [comment]
加了，没用，所以我才想是不是要直接加在magnet链接上

另外，我猜测是不是这些tracker不适用于magnet？

**Comment by XIU2** [comment]
。。。
磁力链接本质上就是 BT 种子，只不过把 BT 种子文件 `.torrent` 做成了去中心化（就像 BT 本身一样），这样无需服务器存储 BT 种子文件，BT 软件下载磁力链接时，就是通过 P2P 寻找其他拥有该种子文件的人，获取到 BT 种子文件 `.torrent` ，然后再通过 BT 种子文件下载资源文件。

**Comment by sjtuross** [comment]
你试试就知道了

**Comment by XIU2** [comment]
你换其他 BT 软件试试吧。
另外并不是所有 Tracker 服务器都会有响应的：
https://github.com/XIU2/TrackersListCollection/blob/master/README-ZH.md#为什么有些-tracker-连不上
