### ISSUE TITLE
BEST Tracker list包含的tracker数量会不会太多了？

### ISSUE THREAD

**Issue by YulinChan** [XIU2/TrackersListCollection#80]
BEST Tracker list包含80多个tracker，比ALL Tracker list的一半还要多，且不说它会增加tracker本身的负担(http://ktetch.co.uk/2014/01/bittorrent-tracker-madness/), 就说这么多tracker有无必要？会不会使得种子文件变的更大从而拖慢下载？另外，在下载资源的时候有DHT和PEX加持，一般热度的种子也能找到很多peers了吧？

所以，我觉得既然是BEST list，在数量上能不能优中选优，进一步缩小tracker数目？

**Comment by XIU2** [comment]
无甚必要~

“会不会使得种子文件变的更大从而拖慢下载？”
Tracker 是在 BT 软件里的，而不是在种子文件里面，而且 Tracker 只是起到**辅助作用**，加了要么**没效果**（没找到更多用户），要么**有效果**（找到更多用户），总之不会起到反效果，你对 Tracker 有很多误解呀。。。

怎么可能会拖慢下载，就算是十几年前的电脑，也不可能性能差到这种地步吧。。。
