### ISSUE TITLE
This is all I know public trackers

### ISSUE THREAD

**Issue by tkp206093** [XIU2/TrackersListCollection#9]
udp://tracker.zer0day.to:1337/announce

udp://tracker.openbittorrent.com:80/announce

https://trackerslis.com

udp://tracker.sith.su:80/announce

udp://tracker.desu.sh:6969/announce

udp://tracker.coppersurfer.tk:6969

http://inferno.demonoid.ph:3415/announce

http://inferno.demonoid.ooo:3418/announce

http://inferno.demonoid.ooo:3410/announce

http://inferno.demonoid.ooo:3395/announce

http://bt.ttk.artvid.ru:6969/announce

http://bt.artvid.ru:6969/announce

http://0123456789nonexistent.com:80/announce

http://0123456789nonexistent.com/announce

http://inferno.demonoid.ph:3392/announce

udp://tracker.ilibr.org:6969/announce

http://www.skyts.net:6969/announce

http://retracker.gorcomnet.ru/announce

udp://eddie4.nl:6969/announce

udp://208.67.16.113:8000/annonuce

udp://tracker.leechers-paradise.org:6969

udp://p4p.arenabg.ch:1337/announce

http://bt.cnscg.com:6969/announce

http://bt.cnscg.org:6969/announce

http://secure.pow7.com/announce

http://retracker.gorcomnet.ru:80/announce

https://newtrackon.com/list

http://0d.kebhana.mx:443/announce

http://104.238.198.186:8000/announce

http://104.28.1.30:8080/announce

http://104.28.16.69/announce

http://107.150.14.110:6969/announce

http://109.121.134.121:1337/announce

http://114.55.113.60:6969/announce

http://125.227.35.196:6969/announce

http://128.199.70.66:5944/announce

http://157.7.202.64:8080/announce

http://158.69.146.212:7777/announce

http://173.254.204.71:1096/announce

http://178.175.143.27/announce

http://178.33.73.26:2710/announce

http://182.176.139.129:6969/announce

http://185.5.97.139:8089/announce

http://185.83.215.123:6969/announce

http://188.165.253.109:1337/announce

http://194.106.216.222/announce

http://195.123.209.37:1337/announce

http://198.177.123.164/announce

http://210.244.71.25:6969/announce

http://210.244.71.26:6969/announce

http://213.163.67.56:1337/announce

http://37.19.5.139:6969/announce

http://37.19.5.155:6881/announce

http://46.4.109.148:6969/announce

http://5.2.79.22:6969/announce

http://5.79.249.77:6969/announce

http://5.79.83.193:2710/announce

http://51.254.244.161:6969/announce

http://52.28.76.37:6969/announce

http://52.29.11.73:6969/announce

http://52.58.128.163:6969/announce

http://59.36.96.77:6969/announce

http://62.210.202.61/announce

http://74.82.52.209:6969/announce

http://80.246.243.18:6969/announce

http://81.200.2.231/announce

http://85.17.19.180/announce

http://87.110.238.140:6969/announce

http://87.248.186.252:8080/announce

http://87.253.152.137/announce

http://91.216.110.47/announce

http://91.218.230.81:6969/announce

http://93.92.64.5/announce

http://[2001:19f0:6c01:1b7d:5400:1ff:fefc:3c2a]:6969/announce

http://[2001:1af8:4700:a032:1234::]:6969/announce

http://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announce

http://[2001:41d0:305:2100::16a3]:6969/announce

http://[2001:470:1:189:0:1:2:3]:6969/announce

http://[2a02:c205:2026:1682::1]:443/announce

http://[2a04:ac00:1:3dd8::1:2710]:2710/announce

http://agusiq-torrents.pl:6969/announce

http://asnet.pw:2710/announce

http://bigfoot1942.sektori.org:6969/announce

http://bt-tracker.gamexp.ru:2710/announce

http://bt.henbt.com:2710/announce

http://bt.pusacg.org:8080/announce

http://bt.xxx-tracker.com:2710/announce

http://bt2.54new.com:8080/announce

http://bt2.careland.com.cn:6969/announce

http://carapax.net:6969/announce

http://denis.stalker.upeer.me:6969/announce

http://fxtt.ru:80/announce

http://grifon.info:80/announce

http://mgtracker.org:2710/announce

http://mgtracker.org:6969/announce

http://newtoncity.org:6969/announce

http://ns349743.ip-91-121-106.eu:80/announce

http://open.lolicon.eu:7777/announce

http://open.touki.ru/announce.php

http://opentracker.acgnx.se:80/announce

http://p4p.arenabg.ch:1337/announce

http://p4p.arenabg.com:1337/announce

http://pt.lax.mx:80/announce

http://retracker.bashtel.ru:80/announce

http://retracker.krs-ix.ru:80/announce

http://retracker.mgts.by:80/announce

http://retracker.spark-rostov.ru:80/announce

http://retracker.telecom.by:80/announce

http://share.camoe.cn:8080/announce

http://sukebei.tracker.wf:8888/announce

http://t.acg.rip:6699/announce

http://t.nyaatracker.com:80/announce

http://thetracker.org:80/announce

http://torrentclub.tech:6969/announce

http://torrentsmd.eu:8080/announce

http://torrentsmd.me:8080/announce

http://tr.cili001.com:8070/announce

http://tr.kxmp.cf:80/announce

http://tracker.aletorrenty.pl:2710/announce

http://tracker.beeimg.com:6969/announce

http://tracker.birkenwald.de:6969/announce

http://tracker.calculate.ru:6969/announce

http://tracker.city9x.com:2710/announce

http://tracker.devil-torrents.pl:80/announce

http://tracker.dler.org:6969/announce

http://tracker.dutchtracking.com:80/announce

http://tracker.dutchtracking.nl:80/announce

http://tracker.edoardocolombo.eu:6969/announce

http://tracker.electro-torrent.pl:80/announce

http://tracker.ex.ua:80/announce

http://tracker.filemail.com:6969/announce

http://tracker.filepit.to:6969/announce

http://tracker.files.fm:6969/announce

http://tracker.filetracker.pl:8089/announce

http://tracker.flashtorrents.org:6969/announce

http://tracker.frozen-layer.net:6969/announce

http://tracker.internetwarriors.net:1337/announce

http://tracker.kicks-ass.net:80/announce

http://tracker.kuroy.me:5944/announce

http://tracker.mg64.net:6881/announce

http://tracker.moeking.me:6969/announce

http://tracker.novg.net:6969/announce

http://tracker.nyaa.uk:6969/announce

http://tracker.port443.xyz:6969/announce

http://tracker.skyts.net:6969/announce

http://tracker.tfile.co:80/announce

http://tracker.tfile.me:80/announce

http://tracker.torrentbay.to:6969/announce

http://tracker.uw0.xyz:6969/announce

http://tracker.ygsub.com:6969/announce

http://tracker1.wasabii.com.tw:6969/announce

http://tracker2.wasabii.com.tw:6969/announce

http://tracker4.emce.org:12345/announce

http://www.wareztorrent.com:80/announce

https://104.28.17.69/announce

https://open.kickasstracker.com:443/announce

https://opentracker.acgnx.se:443/announce

https://t.quic.ws:443/announce

https://tracker.fastdownload.xyz:443/announce

https://tracker.hama3.net:443/announce

https://tracker.vectahosting.eu:2053/announce

udp://104.238.198.186:8000/announce

udp://107.150.14.110:6969/announce

udp://109.121.134.121:1337/announce

udp://114.55.113.60:6969/announce

udp://128.199.70.66:5944/announce

udp://168.235.67.63:6969/announce

udp://178.33.73.26:2710/announce

udp://182.176.139.129:6969/announce

udp://185.225.17.100:1337/announce

udp://185.5.97.139:8089/announce

udp://185.86.149.205:1337/announce

udp://188.165.253.109:1337/announce

udp://191.101.229.236:1337/announce

udp://194.106.216.222:80/announce

udp://195.123.209.37:1337/announce

udp://195.123.209.40:80/announce

udp://208.67.16.113:8000/announce

udp://213.163.67.56:1337/announce

udp://37.19.5.155:2710/announce

udp://45.56.74.11:6969/announce

udp://46.4.109.148:6969/announce

udp://5.2.79.22:6969/announce

udp://5.79.249.77:6969/announce

udp://5.79.83.193:6969/announce

udp://51.254.244.161:6969/announce

udp://52.28.76.37:6969/announce

udp://52.29.11.73:6969/announce

udp://62.212.85.66:2710/announce

udp://74.82.52.209:6969/announce

udp://78.30.254.12:2710/announce

udp://85.17.19.180:80/announce

udp://89.234.156.205:80/announce

udp://91.218.230.81:6969/announce

udp://94.23.183.33:6969/announce

udp://[2001:19f0:6c01:1b7d:5400:1ff:fefc:3c2a]:6969/announce

udp://[2001:41d0:305:2100::16a3]:6969/announce

udp://[2001:470:1:189:0:1:2:3]:6969/announce

udp://[2a03:2c40:10:2163::1]:6969/announce

udp://[2a03:7220:8083:cd00::1]:451/announce

udp://[2a04:ac00:1:3dd8::1:2710]:2710/announce

udp://[2a04:c44:e00:32e0:4cf:6aff:fe00:aa1]:6969/announce

udp://amigacity.xyz:6969/announce

udp://bigfoot1942.sektori.org:6969/announce

udp://bt.aoeex.com:8000/announce

udp://bt.xxx-tracker.com:2710/announce

udp://carapax.net:6969/announce

udp://contrata.putasysexo.com:53/announce

udp://explodie.org:6969

udp://home.penza.com.ru:6969/announce

udp://inferno.demonoid.pw:3418/announce

udp://ipv6.tracker.harry.lu:80/announce

udp://jeremylee.sh:6969/announce

udp://mgtracker.org:2710/announce

udp://newtoncity.org:6969/announce

udp://open.demonii.com:1337

udp://p4p.arenabg.com:1337

udp://peerfect.org:6969/announce

udp://public.popcorn-tracker.org:6969/announce

udp://pubt.in:2710/announce

udp://retracker.baikal-telecom.net:2710/announce

udp://retracker.nts.su:2710/announce

udp://retracker.sevstar.net:2710/announce

udp://santost12.xyz:6969/announce

udp://tc.animereactor.ru:8082/announce

udp://thetracker.org:80/announce

udp://torrent.gresille.org:80/announce

udp://torrentclub.tech:6969/announce

udp://tr.cili001.com:8070/announce

udp://tracker.0o.is:6969/announce

udp://tracker.aletorrenty.pl:2710/announce

udp://tracker.beeimg.com:6969/announce

udp://tracker.birkenwald.de:6969/announce

udp://tracker.cypherpunks.ru:6969/announce

udp://tracker.doko.moe:6969/announce

udp://tracker.dutchtracking.com:6969/announce

udp://tracker.dyn.im:6969/announce

udp://tracker.eddie4.nl:6969/announce

udp://tracker.ex.ua:80/announce

udp://tracker.filepit.to:6969/announce

udp://tracker.filetracker.pl:8089/announce

udp://tracker.flashtorrents.org:6969/announce

udp://tracker.grepler.com:6969/announce

udp://tracker.halfchub.club:6969/announce

udp://tracker.ilibr.org:80/announce

udp://tracker.justseed.it:1337/announce

udp://tracker.kicks-ass.net:80/announce

udp://tracker.kuroy.me:5944/announce

udp://tracker.mg64.net:2710/announce

udp://tracker.mg64.net:6969/announce

udp://tracker.msm8916.com:6969/announce

udp://tracker.novg.net:6969/announce

udp://tracker.open-internet.nl:6969/announce

udp://tracker.piratepublic.com:1337/announce

udp://tracker.pomf.se:80/announce

udp://tracker.port443.xyz:6969/announce

udp://tracker.sktorrent.net:6969/announce

udp://tracker.skynetcloud.site:6969/announce

udp://tracker.skyts.net:6969/announce

udp://tracker.supertracker.net:1337/announce

udp://tracker.torrentbay.to:6969/announce

udp://tracker.trackton.ga:7070/announce

udp://tracker.tvunderground.org.ru:3218/announce

udp://tracker.vanitycore.co:6969/announce

udp://tracker1.itzmx.com:8080/announce

udp://tracker2.christianbro.pw:6969/announce

udp://tracker2.indowebster.com:6969/announce

udp://tracker4.piratux.com:6969/announce

udp://wambo.club:1337/announce

udp://zer0day.ch:1337/announce

udp://zer0day.to:1337/announce

wss://tracker.btorrent.xyz

wss://tracker.fastcast.nz

wss://tracker.openwebtorrent.com

udp://tracker.coppersurfer.tk:6969/announce

udp://tracker.leechers-paradise.org:6969/announce

udp://tracker.internetwarriors.net:1337/announce

udp://p4p.arenabg.com:1337/announce

udp://exodus.desync.com:6969/announce

udp://tracker.tiny-vps.com:6969/announce

udp://tracker.moeking.me:6969/announce

udp://retracker.lanta-net.ru:2710/announce

udp://denis.stalker.upeer.me:6969/announce

udp://tracker.torrent.eu.org:451/announce

udp://tracker.cyberia.is:6969/announce

udp://open.stealth.si:80/announce

udp://tracker3.itzmx.com:6961/announce

udp://open.demonii.si:1337/announce

udp://valakas.rollo.dnsabr.com:2710/announce

udp://tracker.ds.is:6969/announce

udp://retracker.netbynet.ru:2710/announce

udp://opentor.org:2710/announce

udp://zephir.monocul.us:6969/announce

udp://xxxtor.com:2710/announce

udp://tracker.zum.bi:6969/announce

udp://tracker.zerobytes.xyz:1337/announce

udp://tracker.yoshi210.com:6969/announce

udp://tracker.uw0.xyz:6969/announce

udp://tracker.sbsub.com:2710/announce

udp://tracker.nyaa.uk:6969/announce

udp://tracker.nextrp.ru:6969/announce

udp://tracker.lelux.fi:6969/announce

udp://tracker.iamhansen.xyz:2000/announce

udp://tracker.filemail.com:6969/announce

udp://tracker.dler.org:6969/announce

udp://tracker-udp.gbitt.info:80/announce

udp://retracker.akado-ural.ru:80/announce

udp://opentracker.i2p.rocks:6969/announce

udp://open.nyap2p.com:6969/announce

udp://chihaya.toss.li:9696/announce

udp://bt2.archive.org:6969/announce

udp://bt1.archive.org:6969/announce

udp://bt.okmp3.ru:2710/announce

udp://tracker4.itzmx.com:2710/announce

udp://tracker2.itzmx.com:6961/announce

udp://tracker.swateam.org.uk:2710/announce

udp://tr.bangumi.moe:6969/announce

udp://qg.lorzl.gq:2710/announce

udp://bt2.54new.com:8080/announce

http://www.proxmox.com:6969/announce

http://tracker.tvunderground.org.ru:3218/announce

http://tracker.corpscorp.online:80/announce

http://tracker.bt4g.com:2095/announce

http://retracker.sevstar.net:2710/announce

http://mail2.zelenaya.net:80/announce

http://h4.trakx.nibba.trade:80/announce

http://www.loushao.net:8080/announce

http://vps02.net.orel.ru:80/announce

http://tracker2.itzmx.com:6961/announce

http://tracker1.itzmx.com:8080/announce

http://tracker01.loveapp.com:6789/announce

http://tracker.zerobytes.xyz:1337/announce

http://tracker.yoshi210.com:6969/announce

http://tracker.torrentyorg.pl:80/announce

http://tracker.nyap2p.com:8080/announce

http://tracker.lelux.fi:80/announce

http://tracker.gbitt.info:80/announce

http://tracker.bz:80/announce

http://pow7.com:80/announce

http://opentracker.i2p.rocks:6969/announce

http://open.acgnxtracker.com:80/announce

http://acg.rip:6699/announce

https://tracker.parrotlinux.org:443/announce

https://tracker.opentracker.se:443/announce

https://tracker.nanoha.org:443/announce

https://1337.abcvg.info:443/announce

https://tracker.lelux.fi:443/announce

https://tracker.gbitt.info:443/announce

wss://tracker.sloppyta.co:443/announce

wss://tracker.openwebtorrent.com:443/announce

wss://tracker.novage.com.ua:443/announce

udp://62.138.0.158:6969/announce

udp://93.158.213.92:1337/announce

udp://188.241.58.209:6969/announce

udp://80.209.252.132:1337/announce

udp://62.210.97.59:1337/announce

udp://151.80.120.114:2710/announce

udp://151.80.120.112:2710/announce

udp://208.83.20.20:6969/announce

udp://5.206.54.49:6969/announce

udp://35.156.19.129:6969/announce

udp://37.235.174.46:2710/announce

udp://54.37.235.149:6969/announce

udp://91.216.110.52:451/announce

udp://159.100.245.181:6969/announce

udp://185.181.60.67:80/announce

udp://176.113.71.19:6961/announce

udp://142.44.243.4:1337/announce

udp://51.15.40.114:80/announce

udp://184.105.151.164:6969/announce

udp://46.148.18.250:2710/announce

udp://194.182.176.251:6969/announce

udp://212.1.226.176:2710/announce

udp://46.148.18.254:2710/announce

http://184.105.151.164:6969/announce

udp://212.47.227.58:6969/announce

udp://165.227.0.51:6969/announce

udp://51.15.55.204:1337/announce

udp://51.254.249.186:6969/announce

udp://185.83.215.123:6969/announce

udp://149.129.65.231:2710/announce

udp://15.188.67.15:6969/announce

udp://185.97.255.30:6969/announce

udp://51.158.23.91:6969/announce

udp://51.15.134.218:2710/announce

udp://207.246.121.172:2000/announce

udp://52.58.128.163:6969/announce

udp://45.86.70.144:6969/announce

udp://109.72.83.214:80/announce

udp://217.76.183.53:80/announce

udp://185.83.214.123:6969/announce

udp://23.95.32.130:6969/announce

udp://80.211.26.119:9696/announce

udp://207.241.231.226:6969/announce

udp://207.241.226.111:6969/announce

udp://207.180.241.35:2710/announce

https://198.251.90.163:443/announce

http://79.133.36.244:6969/announce

http://91.217.91.21:3218/announce

http://93.158.213.92:1337/announce

http://51.15.134.218:2710/announce

http://153.92.6.117:80/announce

http://78.30.254.12:2710/announce

http://62.210.177.88:1096/announce

http://91.207.136.85:80/announce

http://52.207.93.234:80/announce

udp://95.211.168.204:2710/announce

udp://176.113.68.66:6961/announce

udp://75.127.14.224:2710/announce

udp://51.15.3.74:6969/announce

udp://218.5.42.53:2710/announce

udp://139.99.100.97:8080/announce

https://51.158.23.91:443/announce

http://182.150.53.61:8080/announce

http://95.107.48.115:80/announce

http://95.211.168.204:2710/announce

http://176.113.71.19:6961/announce

http://176.113.68.67:6961/announce

http://34.92.10.197:6789/announce

http://51.15.55.204:1337/announce

http://95.216.171.255:6969/announce

http://62.210.202.61:80/announce

http://51.158.23.91:80/announce

http://176.123.5.118:80/announce

http://51.79.71.167:80/announce

http://185.83.214.123:6969/announce

http://51.68.122.172:80/announce

http://209.141.39.35:6699/announce

wss://tracker.darli.net:6611/announce

http://tracker.ipv6tracker.ru:80/announce

https://tracker.sloppyta.co:443/announce

udp://ipv6.tracker.zerobytes.xyz:16661/announce

https://zqzx.xyz:443/announce

http://tracker.ex.ua/announce

http://tracker.bittorrent.am/announce

http://tracker.kicks-ass.net/announce

http://tracker.dutchtracking.nl/announce

udp://ulfbrueggemann.no-ip.org:6969/announce

http://t1.pow7.com/announce

http://213.159.215.198:6970/announce

http://atrack.pow7.com/announce

http://retracker.krs-ix.ru/announce

http://t2.pow7.com/announce

http://torrent.gresille.org/announce

http://www.wareztorrent.com/announce

https://www.wareztorrent.com/announce

http://tracker.dutchtracking.com/announce

udp://retracker.hotplug.ru:2710/announce

udp://tracker.trackerfix.com:81/announce

http://tracker.bt-hash.com:80/announce

udp://[2001:1b10:1000:8101:0:242:ac11:2]:6969/announc

http://54.39.98.124:80/announce

https://opentracker.xyz:443/announce

https://1337.abcvg.info/announce

http://open.trackerlist.xyz:80/announce

http://tracker2.dler.org:80/announce

udp://45.79.184.106:6969/announce

udp://109.248.43.36:6969/announce

http://opentracker.xyz:80/announce

http://tracker.publictorrent.net:80/announce

https://opentracker.co:443/announce

https://tracker.publictorrent.net:443/announce

udp://u4.trakx.nibba.trade:1337/announce

udp://explodie.org:6969/announce

udp://tracker.opentrackr.org:1337/announce

http://tracker.bittor.pw:80/announce

udp://9.rarbg.com:2710/announce

udp://ipv4.tracker.harry.lu:80/announce

udp://9.rarbg.to:2780/announce

udp://9.rarbg.me:2800/announce

udp://tracker.nibba.trade:1337/announce

udp://bt.dy20188.com:80/announce

http://gwp2-v19.rinet.ru:80/announce

http://sub4all.org:2710/announce

udp://tracker.kamigami.org:2710/announce

http://tracker.kamigami.org:2710/announce

http://open.acgtracker.com:1096/announce

http://tracker4.itzmx.com:2710/announce

http://tracker3.itzmx.com:6961/announce

http://tracker.vanitycore.co:6969/announce

http://tracker.tiny-vps.com:6969/announce

http://tracker.grepler.com:6969/announce

http://tracker.baravik.org:6970/announce

http://torrentsmd.com:8080/announce

http://inferno.demonoid.ooo:3416/announce

http://inferno.demonoid.ooo:3412/announce

http://t.nyaatracker.com/announce

http://tracker.xfsub.com:6868/announce

udp://shadowshq.yi.org:6969/announce

udp://shadowshq.eddie4.nl:6969/announce

http://tracker.tfile.me/announce

https://trackerslis.com/announce

**Comment by XIU2** [comment]
Sorry, the purpose of this project is to integrate other Trackers List projects, and not strictly maintain each Tracker.
***please submit Tracker to the following projects:***

- https://github.com/ngosang/trackerslist
- https://newtrackon.com/
(The project supports manual submissions and monitors Tracker's availability in real time.)
